name: cinneman
description: 'Cinneman: the taste of art'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.9
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  dio: ^5.1.1
  cryptography: ^2.5.0
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  url_launcher: ^6.1.10
  qr_flutter: ^4.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/png/


  fonts:
    - family: Morganite
      fonts:
      - asset: assets/fonts/Morganite-Book.ttf
        style: normal
        weight: 800
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Expanded-ExtraBold.ttf
          weight: 800


